### ISSUE TITLE
Add missing ppma_manage_authors and ppma_manage_layouts capabilities

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#1031]
We seem to have lost ppma_manage_authors, ppma_manage_layouts and others in PublishPress Capabilities:
https://publishpress.com/knowledge-base/admin-area-permissions/

<img width="1089" alt="Screen Shot 2022-11-04 at 4 17 56 PM" src="https://user-images.githubusercontent.com/3868028/200067045-0ffaeb5e-eb4b-49bd-8438-596acef99642.png">

And when I try to add it, I get "Incorrect capability name."

<img width="453" alt="Screen Shot 2022-11-04 at 4 22 25 PM" src="https://user-images.githubusercontent.com/3868028/200067501-56b788ea-f50c-4047-9845-11f64e8dfce8.png">

**Comment by ojopaul** [comment]
@stevejburge Capabilities can't be lost since it's added to roles.

I believe this may be more of capabilities plugin issue and not Authors.

When i searched for the missing capabilities, the seemed to be associated with Taxonomies instead and the customer that needed the assignment can find them their pending the time the issue is fixed while sending it to the appropriate channel.

1. ppma_manage_layouts is in additional tab
2. ppma_manage_authors is in Taxonomies tab under Authors
You can see the screenshot below:

![cap](https://user-images.githubusercontent.com/92122385/200072838-4f73c2eb-8499-48b3-a073-81f9eaa6f6f1.jpg)

**Comment by ojopaul** [comment]
@stevejburge On further look,
'`ppma_manage_layouts`' was just added to free version and wasn't added in '`cme_multiple_authors_capabilities`' filters and that explained why it's in additional layout which I'll make a commit to fix now.

For  '`ppma_manage_authors`', the reason is because the capability is showing under Authors taxonomy as shown in the above screenshot. This is bacause it's a taxonomies capability and since Authors already has it own tab, I think capabilities plugin has to make exception for this. I don't really know how as I haven't work on capabilities before but that's what happen.

So, the capabilities are not lost but currrently showing at the wrong location

**Comment by stevejburge** [comment]
Thanks @ojopaul
