### ISSUE TITLE
What to do with "Meta"?

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#1054]
I wonder what the best approach is to "Meta" now? Email and Site have moved to fields
<img width="560" alt="Screen Shot 2022-11-10 at 12 04 11 PM" src="https://user-images.githubusercontent.com/3868028/201160208-e85b1784-06a4-406e-83b9-0bf94eba5691.png">

**Comment by ojopaul** [comment]
I don't thin we should really border about it if we have intention of making migration from twig layout easier. The default templates from twig layout are meta dependant.

We already make the best approach by making it possible to disable the meta.

For advance user, they can disable the meta and create their own complete meta row.

If your concern is the fact those fields are not staying next to meta items, that's something that can be done by simply changing meta html tag from div to span to make it inline.

Since it can be disabled, why worrying about it if it add compatibility to previous layout styles? @stevejburge

**Comment by stevejburge** [comment]
Thanks. Maybe this becomes the "View All Posts" tab?

If possible, I'd like to hide those old email and site fields from this tab. Related:
https://github.com/publishpress/PublishPress-Authors/issues/960

**Comment by ojopaul** [comment]
@stevejburge if we remove the meta the way it is, the default boxes like "Boxed", "Centered" etc will be affected, I'm wondering why we spend much effort creating the default layout to match box if they'll end up been useless?

That aside, what happen to layouts that uses it?

Are we removing the default boxes since they're created with meta in mind or what solution do you have for them and most especially, user that already has the installation and may be using the boxes?

We'll simply remove it?

**Comment by stevejburge** [comment]
@ojopaul All good questions.

Maybe this is something we drop in a future version.

Let's delay a decision on removing these.

**Comment by ojopaul** [comment]
@stevejburge Whatever decision we make, just know it won't be easy to drop.

The best time to drop them would have been not adding them at all in author boxes as we can't just remove what could potentially affect existing users layouts.

**Comment by ojopaul** [comment]
@stevejburge Whatever decision we make, just know it won't be easy to drop.

The best time to drop them would have been not adding them at all in author boxes as we can't just remove what could potentially affect existing users layouts.

Maybe if you have answer to compatibility with the default layouts like "Boxed" that already exist in user database and may be using, then that'll make sense on removing it.

Here's a good example, if we remove it today, that shows "Boxed", "Centered" will have that section completely removed in their design. What happen to user using it?

We'll create another new default layouts and call existing one legacy then ask them to migrate to it?

**Comment by stevejburge** [comment]
@ojopaul Yes, very true. 

Replacing old features with new and improved versions can be a headache
