### ISSUE TITLE
Add  Dashicons and Fontawesome icon pages link to Author Boxes profile icon field

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#1064]
We have a "Display Icon" field. Can we help people understand what icons are available to them?

How would I find the code for a TikTok or WhatsApp icon, for example?

<img width="934" alt="Screen Shot 2022-11-10 at 1 12 10 PM" src="https://user-images.githubusercontent.com/3868028/201174240-9edd74a1-8e6f-403a-9b61-404c5c08e6da.png">

**Comment by ojopaul** [comment]
@stevejburge Do you want us to link to https://developer.wordpress.org/resource/dashicons/ and https://fontawesome.com/icons?

Better still, can you elaborate on what the description should updated to?

**Comment by stevejburge** [comment]
@ojopaul Good question. Maybe this has to be a documentation article?

I'm not sure what's possible here. Can people use icons from any URL they choose?

**Comment by ojopaul** [comment]
URL is not icon. That's why we have example.

People can use external icon or site icon that's loaded on their site.

- dashicons is loaded in wordpress except another plugin dequeue it
- We included a settings to load fontawesome icon styles in our settings and that's why those options is most easy.

If you want us to add image option, maybe that worth it but it'll be another field

**Comment by stevejburge** [comment]
@ojopaul Thanks. OK, so Dashicon and Fontawesome are included in Authors

Maybe the advanced approach is to offer 3 choices?

1. Dashicons
2. Fontawesome
3. Custom image

**Comment by ojopaul** [comment]
Custom image can't stay in same field.
We'll need to add new field for custom image and have image as option like this "Field Image + Field Icon + Prefix + Value + Suffix" so user can choose any of the options or their combo.

The reason image can't sit with icon is because image require other configuration like width, height, radius etc which doesn't apply to icon.

If we need a documentation, image and icon still doesn't below to same group.

In addition, do you mind giving the text for the display icon field and documentation link?

**Comment by stevejburge** [comment]
OK, should we just offer Dashicons and Fontawesome for now?

We can prefill sample code for those two. For example:

<span class="dashicons dashicons-users"></span>
The description can have a link to https://developer.wordpress.org/resource/dashicons/
