### ISSUE TITLE
Authors widget not loading with full-site editing

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#1123]
This could be related to https://github.com/publishpress/PublishPress-Authors/issues/1122

<img width="447" alt="Screen Shot 2022-12-12 at 9 30 23 AM" src="https://user-images.githubusercontent.com/3868028/207071113-912f5ee4-32fa-44b9-bcb8-bb2f1ec10689.png">

**Comment by ojopaul** [comment]
@stevejburge I believe your screen is post/page screen and if so, you're looking for widgets in blocks which is no longer happening in latest WordPress and themes that are block based.

The most realistic thing we can do is creating blocks equivalent of our our widgets since it's legacy in WordPress.

Note, if you're on a theme that support widget, the Authors widget will show.

**Comment by stevejburge** [comment]
@ojopaul Understood, I'll move this to a new milestone
