### ISSUE TITLE
Should we add a setting for which user roles can be added as Authors?

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#1134]
It might be good to have a user role setting

> even though users with the role "Subscriber" and "Contributor" can be added as "Authors" in Admin User's account, "Author Profile" will not appear in their dashboard once they login (screenshots attached). Also, since user with the role "Subscriber"  can only read the content and post comments - he might not need the option to be added as author at all. 

Screenshots for those roles, after adding them as authors

<img width="1262" alt="Screen Shot 2022-12-22 at 2 54 47 PM" src="https://user-images.githubusercontent.com/3868028/209215740-468db3eb-6974-4a01-bae7-e519b9a8d537.png">
<img width="1211" alt="Screen Shot 2022-12-22 at 2 54 41 PM" src="https://user-images.githubusercontent.com/3868028/209215748-b627da97-77fd-4107-a1ce-4085f6ebbfb0.png">

**Comment by ojopaul** [comment]
![s](https://github.com/publishpress/PublishPress-Authors/assets/92122385/8c216880-999e-4eb1-bc0b-e8590e673a28)

@stevejburge 
1. We have the above settings to determine which roles are added as Authors. Not selecting subscriber in the above settings is more than enough and that way, subscribers users won't be added as Author when their account is created.
2. The part of subscribers not been able to see their Author's profile is not true either. In as much the role have `ppma_edit_own_profile`, they'll see option to edit their Author's profile
3. Only roles with `edit_posts` are available for selection in Mapped Authors which shows by default, subscribers are not even available for selection unless they have the `edit_posts` capability or automatic account creation is enabled for their role.

So, i believe this new field suggestion is totally unneeded as the reasons provided in the issue description are either not true or lack of knowledge on how Authors works or it could be outdated due to the fact the issue is like 8 months old.

**Comment by stevejburge** [comment]
@ojopaul I wonder if this is connected to this problem?
https://github.com/publishpress/PublishPress-Authors/issues/1443

**Comment by stevejburge** [comment]
@ojopaul We don't. I think we just need the ppma_edit_own_profile fix
