### ISSUE TITLE
Create a single page or widget to show Authors

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#124]
>  want to have a contributor page like Unherd.com (https://unherd.com/writers/)
> where the article shows the author and then when clicked it shows the authors details.
<img width="1340" alt="Screen Shot 2020-05-12 at 10 07 15 AM" src="https://user-images.githubusercontent.com/3868028/81701720-67df7a80-9438-11ea-9183-33cfde57679a.png">

One flexible approach to this could be creating a widget that show a single authorr and their posts.

**Comment by stevejburge** [comment]
One more request on these lines

> how can i display all “guest authors” on a page?

**Comment by stevejburge** [comment]
One more request:

> creating a page that lists all authors contributing on the website. Something similar to what this plugin does https://wordpress.org/plugins/authors-list/. It would be great to be able to show some authors at the top/with higher priority, for example, the chief editor or executive director would be at the top of the page.

This would also involve this feature: https://github.com/publishpress/PublishPress-Authors/issues/58

**Comment by stevejburge** [comment]
One more:

> Is there a way to display all authors, using your PP Authors plugin? Like an archive page?

**Comment by stevejburge** [comment]
One more request for this

**Comment by stevejburge** [comment]
One more:

> 
It would be nice to have an index page where people can browse authors, alphabetically sorted by author's last name, with a top-menu of the alphabet, linked from each letter to a page listing all author last names starting with that letter, linking to each author's page. Any prospect of finding that in the PRO version? Or if not now, then maybe in the future? (see example screenshot below of another website I manage)

![bceFb0U4xJbshm0j](https://user-images.githubusercontent.com/3868028/164238992-200055fa-36aa-4020-9242-1b746174ebdc.png)

> - building on that last idea, I would like to have a widget sporting an alphabet list linking to each index letter page, listing links to author's pages (see example screenshot below of another website I manage):


<img width="385" alt="Screen Shot 2022-04-20 at 9 16 47 AM" src="https://user-images.githubusercontent.com/3868028/164239028-588cbd45-cf38-4e73-83e3-06a33c6ad3c4.png">

**Comment by stevejburge** [comment]
Another example: https://niemanstoryboard.org/authors/

<img width="1192" alt="Screen Shot 2022-04-22 at 1 17 16 PM" src="https://user-images.githubusercontent.com/3868028/164763149-76bf90f5-b841-4a8a-9271-c169f2585e6f.png">

**Comment by stevejburge** [comment]
Maybe we can take a shortcode approach to this and build on top of [publishpress_authors_list]?

**Comment by ojopaul** [comment]
@stevejburge this will come in handy when making documentation.

We introduced new layout and additional parameters.

The new introduced layout is:
- `authors_index`
- `authors_recent`

In addition to the new layout, i added more parameters and they are:
- `limit_per_page` (option to limit result per page, when this is set, pagination will automatically be enabled)

- `show_empty` (options: 1,0) (whether to show user without post or not where 1 is true while 0 is false)

- `authors` => (options: guests,users) whether to show only guest authors or users authors Default to all when not provided. This option doesn't work with pagination when provided and all authors or guests will be displayed without pagination

- `authors_recent_col` (options: 2, 3, 4 etc default to 4). This is an optional parameter introduced mainly for authors_index layout. In my testing, due to the fact the shortcode stays inside content, i noticed 4 column doesn't perform well unless the shortcode is used on a fullpage. So, i introduced authors_recent_col and can be tested like this sample [publishpress_authors_list layout="authors_recent" limit_per_page="12" authors_recent_col="3"]

- `order` (options: asc, desc) Default to asc

- `orderby` (options: name, count). Whether to order by name or post count. Default to name.

Here's a good testing shortcode for testing new layouts.

1. `[publishpress_authors_list layout="authors_index" show_empty="1"]`
2. `[publishpress_authors_list layout="authors_recent" show_empty="1" limit_per_page="12"]`

The newly introduced pagination will help those with large authors base as they can simply set limit_per_page parameter which was a problem in previous [publishpress_authors_list] that automatically list all users.
