### ISSUE TITLE
Issue with italian translation

### ISSUE THREAD

**Issue by ojopaul** [publishpress/PublishPress-Authors#1253]
![it](https://user-images.githubusercontent.com/92122385/218124777-5c37a580-d64d-482c-9ce1-4409b7c26c8e.jpg)

**Comment by MatteoGheza** [comment]
This is a critical bug. If your site is running on PHP8, and your language is set on Italian, you cannot use any post edit page, it displays an error message because the wrong `sprintf` format syntax.
Please release an update ASAP.

**Comment by ojopaul** [comment]
@wocmultimedia Please take note of this placeholder when next you're translating. I'll fix it again for next version but it seems to keep coming back when you send update

**Comment by wocmultimedia** [comment]
> 

@ojopaul I see it now. Something happened during translation because usually I review all these placeholders which create problems to us translators. Thanks for pointing it out. I have not translating authors since January. Please, fix it and I will do next  update.

**Comment by wocmultimedia** [comment]
Hi @ojopaul,
I found where in my local machine was the problem and solved it. So next version will not have this issue again. I also updated the string in the WP system. Please, have a check. https://translate.wordpress.org/projects/wp-plugins/publishpress-authors/stable/it/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=14918172&filters%5Btranslation_id%5D=103446000

I apologize for the inconvenient but since January I was in standby without translating till last week.
