### ISSUE TITLE
Support custom post types in the authors page

### ISSUE THREAD

**Issue by andergmartins** [publishpress/PublishPress-Authors#13]
The user could have the option to include the selected post types in the authors page. By default we only display 'posts'. Is this the default for WP or is this a limitation imposed by the query in the file core/Classes/Query.php:133?

If default by WP this can be added to the Pro version. Otherwise it should be fixed in the Free package.

**Comment by andergmartins** [comment]
Duplicated? #140

**Comment by ellegaarddk** [comment]
It's really a missing function. At one website we use CPT for published papers - to distinguish it from ordinary news posts - as well as having guest authors write pages. But since only the editor writes the posts, he's the only one with anything listed on the author page.

I manage other website, where the function would be useful, but with no support for CPTs there's no point installing it.

**Comment by andergmartins** [comment]
Thanks for the feedback @ellegaarddk. We still don't have a deadline but we are aiming to add this as a new feature.
