### ISSUE TITLE
RankMath Schema (Logo & Location) Issue

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Authors#1380]
The original report is from: https://wordpress.org/support/topic/rankmath-is-suggesting-there-is-a-schema-code-error-with-author-plugin/page/2/

The user got error when validating on validator.schema.org
![image](https://github.com/publishpress/PublishPress-Authors/assets/83811723/2d56febc-2f82-4590-a868-81225c5d125e)

The issue disappeared when deactivate PublishPress Authors

**Comment by ojopaul** [comment]
Note on this:
We're still not able to replicate this on the update version due to inability to enable location.

Till then, this will be pending till we have a staging site to test with

**Comment by danielclow** [comment]
This issue is caused when you specify that your website represents an "Organization" in Rank Math and then enable the PublishPress Authors plugin. The PublishPress Authors plugin changes "Organization" to "Person".

Reproduction steps:
1. Install Rank Math
2. In the Rank Math dashboard, ensure that **Schema** is enabled
3. Select Rank Math > Titles & Meta > Local SEO
4. In the "Person or Company" area, select **Organization**
5. Check the schema on your homepage generated by Rank Math - it is correct.
`<script type="application/ld+json" class="rank-math-schema-pro">{"@context":"https://schema.org","@graph":[{"@type":"Organization","@id": ...`
7. Install PublishPress Authors
8. Refresh your homepage and check the schema again - the @type is changed to "Person".
`script type="application/ld+json" class="rank-math-schema-pro">{"@context":"https://schema.org","@graph":[{"@type":"Person","@id":`
9. Deactivate PublishPress Authors and the @type changes back to "Organization"

**Comment by Modsed** [comment]
@stevejburge @ojopaul  My site is experiencing this exact same issue, Version 4.4.0

**Comment by ojopaul** [comment]
Thanks for the full details @danielclow

I've moved your report to another issue https://github.com/publishpress/PublishPress-Authors/issues/1708 as it may not be related to original report about schema error when validating url on schema.org.

Your report is about Authors plugin changing Organization to Person which I'll be working on right now and if I have any question, I'll let you know on the thread https://github.com/publishpress/PublishPress-Authors/issues/1708

**Comment by ojopaul** [comment]
While working on the issue now, I realized both are linked and probably the same.

So, Thanks for the detailed information on how to replicate it @danielclow
