### ISSUE TITLE
There is an overlap between the title and the authors’ boxes.

### ISSUE THREAD

**Issue by AnnaShch17** [publishpress/PublishPress-Authors#1567]
**Expected results**: Title should appear above the authors’ boxes.
**Actual results:** Title overlaps with authors boxes.

**Steps to reproduce:**

1. Login to WordPress site as admin.
2. Under admin menu, click “Authors”, then click “Author Boxes”.
3. Click “Simple List” layout (as an example).
4. “Edit Author Box” opens.
5. In the “Bottom Space” field, enter negative value. 
6. Click button “Update”.
7. There is an overlap between the title “Post Authors” and the authors’ information.

OS – Windows 11, browser – Google Chrome, WordPress version 6.3.2, Theme – Twenty Twenty-Three.

Simple List layout.

![Simple List](https://github.com/publishpress/PublishPress-Authors/assets/133815310/9db98daf-0f12-49a1-b446-97063e2a6d70)

Inline with Avatars layout.

![Inline with Avatars](https://github.com/publishpress/PublishPress-Authors/assets/133815310/697b6c6d-89d0-45d9-a709-3f0857767093)

Inline layout.

![Inline](https://github.com/publishpress/PublishPress-Authors/assets/133815310/a57fee82-160c-4597-9bae-a529efc566ad)

Centered layout.

![Centered](https://github.com/publishpress/PublishPress-Authors/assets/133815310/22a41fa2-65e7-48e5-a60a-0504e3d4a04a)

Boxed layout.

![Boxed](https://github.com/publishpress/PublishPress-Authors/assets/133815310/715a2713-3880-4664-818f-6e3bcab2c976)

**Comment by ojopaul** [comment]
@stevejburge @AnnaShch17 The overlap is as a result of negative value you entered for Bottom Space and negative value is a valid styling value as far as bottom space is concerned.

If you enter -10, it shows you want the content to overlap up minus normal which make sense depending on what you're trying to do and could give the result you want with other style attribute but in your case, it doesn't because you simply enter that to see what happen which I don't think it make sense to remove a valid style property because another user doesn't know it usefulness.

A good example of this situation is like complaining a text not displaying on the screen when you give it both background color and text color same value like
```
background: red;
color: red;
```

That doesn't mean those value are useless but in real sense, it's the usage that's wrong.
