### ISSUE TITLE
iPhone editing issue

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Authors#1599]
There is an issue with editing a post in iPhone
https://youtube.com/shorts/rNNDKragRj0?feature=share

**Comment by ojopaul** [comment]
@rizaardiyanto1412 @stevejburge What do you guys suggest here? To me, some features are not meant for mobile.

In the case of that video, the mobile keypad is covering the box when it come up which I'm not sure other way to fix this since Keyboard will always come up to type and considering the author position close to the bottom of the page, it'll always cover it

**Comment by stevejburge** [comment]
@ojopaul OK, we can safely skip this one
