### ISSUE TITLE
Remove dead language files

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#1619]
Can we remove they empty language files? They seem to be interfering with user translations
https://github.com/publishpress/PublishPress-Authors/tree/development/languages
![Screenshot 2024-01-15 at 1 14 33 PM](https://github.com/publishpress/PublishPress-Authors/assets/3868028/43c0d608-9d1e-40e9-82f2-f02cd65d61ae)

**Comment by ojopaul** [comment]
@stevejburge What do you mean by empty translation? They are not empty but only outdated because the translation is not been done.

Here are the ones I check and they're not empty:
- https://github.com/publishpress/PublishPress-Authors/blob/development/languages/publishpress-authors-sv_SE.po
- https://github.com/publishpress/PublishPress-Authors/blob/development/languages/publishpress-authors-ru_RU.po
- https://github.com/publishpress/PublishPress-Authors/blob/development/languages/publishpress-authors-pt_BR.po

**Comment by stevejburge** [comment]
OK, true. Not entirely empty. We can leave this. I'll talk with the user
