### ISSUE TITLE
Warnings for Class MultipleAuthors

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#165]
> I cloned the plugin from Github repo and after cloning it and activating the plugin, I got fatal errors for several classes not found.

<img width="1231" alt="Screen Shot 2020-07-29 at 1 38 42 PM" src="https://user-images.githubusercontent.com/3868028/88807884-385f2500-d180-11ea-976d-773008237efc.png">

**Comment by andergmartins** [comment]
@stevejburge Yes, that is expected. I will add more details or a warning to the repo's readme file. 
We can't just download the repo and install, we need a built package from github.com/publishpress/PublishPress-Authors/releases/

That happens because I don't add the vendor folder to the repository, since I'm following the composer's recommendation for good practice. Adding the vendor folder would increase the repository size and sometimes make a mess due to internal .git folders that can exist in external libraries.
The vendor folder only exists on my local environment, or on the build time.

Those missed classes and other dependencies are loaded by composer and the autoload code, plus the external dependencies are only added to the repo after we run `composer update`.

**Comment by stevejburge** [comment]
Thanks @andergmartins. Closing.

**Comment by andergmartins** [comment]
Just as a reference for future, here is the content that will be added to the readme files:

```
## Installation

:warning: **Warning! This plugin requires to be built before being installed!**

This repository doesn't store external dependencies required by the plugin.
It's not possible to simply clone or download the repository code and have a working WordPress plugin.

We aim to follow good practices on development, and we are using Composer as dependency manager,
which recommends to not add external dependencies into the repository. You can find more information on
their documentation page: [Should I commit the dependencies in my vendor directory?](https://getcomposer.org/doc/faqs/should-i-commit-the-dependencies-in-my-vendor-directory.md)

## How to install?

You can download a built package from [releases page](/releases/) and install it on your WordPress sites by
uploading the zip file.

## How to build a package?

Please, check the instructions on our [documentation pages](https://publishpress.github.io/docs/deployment/building).
```

And here the documentation teaching how to build packages: https://publishpress.github.io/docs/deployment/building
