### ISSUE TITLE
Replace Show Author Field with Hide Author Field in Author Boxes

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#1723]
Can we improve these steps?

- I enable the Twitter field
![Screenshot 2024-04-22 at 12 26 32 PM](https://github.com/publishpress/PublishPress-Authors/assets/3868028/24c61d26-dac5-4fad-85a5-dddb4c4c336a)

- I have Twitter data in the profile
![2](https://github.com/publishpress/PublishPress-Authors/assets/3868028/4a595ff3-5c34-4746-a924-b1fd6df74f29)

- I enable the Twitter field for the Author Box. And nothing happens ...  Can we make enable this by default?
![3](https://github.com/publishpress/PublishPress-Authors/assets/3868028/a3f17cd2-24da-43ef-bec7-cdbbf7e358f6)

**Comment by ojopaul** [comment]
@stevejburge It's not possible for Twitter to show in your profile if enabled from an Author Box as that setting control that specific Author Box and not even all Author box that could have a different setting not to talk of Author Field.

What determine if a field Show in Author Profile is Author Field Configuration, it would maybe be reasonable to add the Author Box settings as condition as well but that's impossible due to possibility of having an Author Box that could have different configuration.

Author field is independent from Author box and author boxes are more than one which each of them can have different configurations.

Going by your logic, that shows when "Show Twitter" is enable for any author box, we automatically show them when user are editing their profile and when it's disabled for another author field, we remove it from user profile edit which I don't think make sense as there's high chance of at least one Author Box having the field disabled.

We have 2 options here if we feel there's an extra step to enable Author Field in Author box which are:
1. Remove the "Show Twitter" option from Author Box (That leaves a problem of all fields showing on all author box even if user don't want it in as much a user has the entry in their profile)
2. Change "Show Twitter" option to "Hide Twitter", this way, all fields are enabled by default and only those specifically disabled won't show in an individual Author Box

In essence, Author Box is not a single settings and Author Fields are only a component used in Author Box.

**Comment by stevejburge** [comment]
Thanks for the detailed write-up @ojopaul 

I do like Option #2. I think we'd really be helping our users if these key fields were set up for them. Right now, it's a lot of work to configure this.
