### ISSUE TITLE
Author Fields ordering

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#1724]
The Author Fields keeps getting organized by "Title" which is confusing as Active and Disabled fields are side-by-side:
![Screenshot 2024-04-22 at 12 50 10 PM](https://github.com/publishpress/PublishPress-Authors/assets/3868028/af973394-9730-4733-aed9-33d59c0e4ba9)

**Comment by ojopaul** [comment]
@stevejburge Sorry, couldn't really understand your request well here. Do you mean we should change the display default order by active first and then inactive last instead of date?

**Comment by stevejburge** [comment]
@ojopaul This is what I see when I first install Authors Pro
![Screenshot 2024-04-24 at 9 23 57 AM](https://github.com/publishpress/PublishPress-Authors/assets/3868028/8111077d-2d45-42f6-b742-352303879831)

It seems like a random order? This is what we see on the Author Profile screen:

![Screenshot 2024-04-24 at 9 24 44 AM](https://github.com/publishpress/PublishPress-Authors/assets/3868028/92f57668-43b3-41ae-b432-7ba6deb26d0a)

**Comment by ojopaul** [comment]
@stevejburge It's not random, the reason others are not showing in Author Field is because they're disabled. Otherwise, you'll see them in order. The only difference is default wordpress field been added first in profile field which are name, email.

Now, back to this issue, what do you want us to do?

**Comment by ojopaul** [comment]
@stevejburge It's not random, the reason others are not showing in Author Field is because they're disabled. Otherwise, you'll see them in order. The only difference is default wordpress field been added first in profile field which are name, email.

Now, back to this issue, what do you want us to do?

Example:, 
Change default order by active first, then disable last and does this affect the way the field show when editing the profile too which shows First Name and Last Name are no longer prioritised or we should order the default in specific order by default or we should order by name etc?

**Comment by stevejburge** [comment]
@ojopaul Can we default to showing the fields the way they are in the "Author Profile" screen?

**Comment by ojopaul** [comment]
@stevejburge Does inactive field shows in Author Profile?

**Comment by ojopaul** [comment]
@stevejburge Does inactive field shows in Author Profile?

If you enable all those disabled fields and go to user profile, did you get a different order?

**Comment by ojopaul** [comment]
@stevejburge Does inactive field shows in Author Profile?

If you enable all those disabled fields and go to user profile, did you get a different order as Author Fields actually has a drag and drop features for Order which shows no way the order will be different.

The reason it looks different is because disabled fields are not display on Author profile.

Reason I asked you to enable those fields(that are skipped on the author profile because they are disabled) and then check again if the order are different.

**Comment by stevejburge** [comment]
Thanks @ojopaul. OK, I see what you're saying here.

I wonder how we can make this easier to understand for new Pro users? 

Maybe the problem goes away when we enable fields by default. I think it probably does ... right now, this ordering is confusing. But if the Pro fields are all enabled, it will make far more sense.

So I'm going to close this in favor of https://github.com/publishpress/PublishPress-Authors/issues/1723

![Screenshot 2024-04-25 at 11 10 03 AM](https://github.com/publishpress/PublishPress-Authors/assets/3868028/6f948964-2154-476d-9274-8a1f3066b91b)

**Comment by stevejburge** [comment]
I'm still seeing this on a new site. Could we give all those social fields a lower order so they appear below the Active fields?
