### ISSUE TITLE
Flip the "Hide" setting

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#1851]
I know it's probably too late but is there any way to flip this setting to be "Show First Name" instead of "Hide First Name"?
![Screenshot 2024-06-21 at 2 54 28 PM](https://github.com/publishpress/PublishPress-Authors/assets/3868028/2c64692f-d46c-48e0-aa0c-095201bf3234)

**Comment by ojopaul** [comment]
@stevejburge Ins't that what we have before this conversation https://github.com/publishpress/PublishPress-Authors/issues/1723 and changes? I think we should be agreeing on implication of some changes instead of going in circle as I just keep creating unnecessary installation every release to migrate the settings. 

And are you finally okay with new Author Fields showing up in Author boxes until they Hide it in Author Boxes Field settings as that's the reason we made this change before

**Comment by stevejburge** [comment]
You're right, sorry. I'm overthinking this. Let's close the issue. It's great that the fields show up as they do now.
