### ISSUE TITLE
Stop Co-Authors Plus import from happening automatically

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#203]
At the moment, PublishPress Authors will automatically import from Co-Authors Plus.

As soon as Authors is installed, the import starts.

This often leads to users being confused by all the users with cap- in their URLs
![Screen Shot 2020-08-24 at 9 39 38 AM](https://user-images.githubusercontent.com/3868028/91051245-d3b3b080-e5ed-11ea-9458-34fddf7868f9.png)
![Snap9](https://user-images.githubusercontent.com/3868028/91051248-d4e4dd80-e5ed-11ea-8c53-660528cb8273.png)

**Comment by andergmartins** [comment]
We can't actually stop it because both plugins use the same taxonomy: authors. So we are not actually importing the data yet, just using the same taxonomy. Co-Authors Plus use the prefix "cap-" for any author, so that is just being displayed there. We have a maintenance task available for fixing that, which removes the "cap-" prefix from the authors, fixing this.
But sue to the bug #206 we are loosing an important Co-Authors Plus data when we install our plugin. I need to fix that bug first. So people will still see the `cap-` prefixed authors, but once they run the migration task we provide (as described here https://github.com/publishpress/PublishPress-Authors/issues/204#issuecomment-680249579) that is fixed.

**Comment by andergmartins** [comment]
@stevejburge I found some bugs in the Co-Authors migration and fixed on the issue #206. The `cap-` prefix will still be visible until the user manually runs the "Copy Co-Authors data" task in the maintenance tab.

**Comment by stevejburge** [comment]
Great, thanks @andergmartins. I'll update the documentation with the next release.

Maybe we add a message for people who install Authors on top of CAP?
