### ISSUE TITLE
Doesn't install nicely with CoAuthors Plus

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#25]
We should make Authors play more nicely with CoAuthors Plus

This is what happens if the too are installed together:

```
( ! )  Fatal error: Cannot redeclare cap_get_coauthor_terms_for_post()  (previously declared in  /app/public/wp-content/plugins/publishpress-authors/publishpress-authors.php:237)  in /app/public/wp-content/plugins/co-authors-plus/co-authors-plus.php  on line 1900
--

```

<img width="778" alt="Screen Shot 2020-02-16 at 10 22 05 AM" src="https://user-images.githubusercontent.com/3868028/74607345-327bf880-50a6-11ea-8560-a7ccd357056f.png">

**Comment by andergmartins** [comment]
@stevejburge I think this happens only if you activate Co-Authors Plus after PublishPress Authors is activate. If you do the inverse, it seems to work. The problem is that our plugin check before declaring that function, but Co-Authors deosn't. We can't fix this on our side, unless we disable the backward compatibility functions to Co-Authors.

**Comment by stevejburge** [comment]
No problem - I'll close this out then.
