### ISSUE TITLE
Add support for structured data for authors for RankMath SEO Plugin.

### ISSUE THREAD

**Issue by andergmartins** [publishpress/PublishPress-Authors#391]
Here is an example of structured data with multiple authors:

<img width="614" alt="Screen Shot 2021-03-08 at 18 36 55" src="https://user-images.githubusercontent.com/407131/110385215-70471880-803d-11eb-97f7-e2a38bb3d944.png">

Here is an example of filter that can be used for adding the authors data:

https://rankmath.com/kb/automate-faq-schema-with-acf-repeater-fields/

**Comment by andergmartins** [comment]
We support YoastSEO but not RankMath Pro.

**Comment by ojopaul** [comment]
@andergmartins I think you created this issue with the mindset of you been the one to work on it. So, as a result, I didn't really understand what we're working on fully.

1. Where did you check the data on the screenshot added to the issue? I believe I'll need to check as well for confirmation when done.
2. Does the issue affect only Guest Authors/ User Authors or both since by default, there shouldn't be issue with user authors since they're WordPress users. Unless the issue is about adding entry when there's more than one author
3. Is the affected page article(post) page or authors profile page?

**Comment by andergmartins** [comment]
Hi @ojopaul you're right, sorry about that.

1. I was using this tool for checking the microdata outputted in the pages (there are 2 options now, I think I was using the markup validator at the time): https://developers.google.com/search/docs/appearance/structured-data

If you are working on a local site, you can copy the HTML code and paste on the code snippet option.

2. It affects both type of authors. Yes, you need to handle it to make sure the correct author is displayed if multiple authors are set for the post.

3. Both.

**Comment by ojopaul** [comment]
Thanks @andergmartins
