### ISSUE TITLE
Build our own Author Profile Pages

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#417]
One common problem is conflicts with plugins (mostly Yoast) and themes when it comes to Author Profile Pages.

Could we consider building our own profile pages in Authors?

**Comment by stevejburge** [comment]
@ojopaul Suggests it may be better to use taxonomy pages and not a custom post type

**Comment by andergmartins** [comment]
@stevejburge @ojopaul Maybe a problem with this feature is we stop having compatibility issues with 3rd part plugins that implement author profile pages, but start having issues with themes that won't implement support for that, at least initially.

But if implemented, creating pages/posts (or custom post type) for each user sounds odd to me, because we would need to keep that updated for new authors, or syncing information for every change in author data. Would require data migration as well, as @ojopaul pointed out on the chat.

I agree with @ojopaul that using taxonomy pages makes more sense, considering it can be more dynamic and straightforward, taking advantage of taxonomy API, and hopefully, the taxonomy support by the themes. If needed, users could create custom templates for that filtering by `author` taxonomy. One problem is that it will display the author page as a standard taxonomy page by default, for all the themes. And it requires to override the routes, to make sure `/authors/` redirect to the correct page.

I think this should be an optional feature, not enabled by default. For avoiding duplicated content harming SEO, we do need to deactivate the WP native author pages, and detect other plugins like Yoast and stop their author profile pages as well.

It worth making sure that the main SEO plugins won't list multiple author profile pages on the sitemap XML.
