### ISSUE TITLE
There are no default layouts in "Layout" menu item

### ISSUE THREAD

**Issue by JulieBanu** [publishpress/PublishPress-Authors#49]
Go to Authors >   Layout
Note: there are no default layouts in the   "Layout" menu item

![NoDefaultLayouts](https://user-images.githubusercontent.com/62157750/77197471-7a75ad00-6aa2-11ea-9edc-9514db8efe1a.PNG)

**Comment by andergmartins** [comment]
Hi @JulieBanu thank you for reporting the issue. This happens when the update method is not executed properly by the plugin. 
Please, could you try to load Settings > Maintenance > Create default layouts and check if they are created?

Btw, we will try to find out why those layouts didn't install. 
Thanks

**Comment by JulieBanu** [comment]
Hi @andergmartins 
After following the steps that you mentioned (load Settings > Maintenance > Create default layouts) 
I checked again and the default layouts appeared. 

Thank you

**Comment by andergmartins** [comment]
Cool, you're welcome.
Thanks for the feedback.

**Comment by andergmartins** [comment]
Sorry, I closed this but I'm reopen it because we need to find a way to prevent this to happen again... or implement a warning that shows to the user with the option to run the maintenance task (dismissible notice).
