### ISSUE TITLE
There is no "Remove author from new posts" option

### ISSUE THREAD

**Issue by JulieBanu** [publishpress/PublishPress-Authors#54]
Step 1:   Install and activate "PublishPress Authors" plugin, the Pro version

![PublishPressPro](https://user-images.githubusercontent.com/62157750/77685402-a5f01000-6f58-11ea-91cd-e30d5cb05fb5.PNG)

Step 2:   Go to "Authors"
Step 3:   Go to "Settings"
Note:   there is no "Remove author from new posts" checkbox option

![NoAuthors](https://user-images.githubusercontent.com/62157750/77685471-b86a4980-6f58-11ea-8495-ca6c3c3646f1.PNG)

**Comment by andergmartins** [comment]
HI @JulieBanu, thank you for getting in touch.
Sorry, we probably didn't communicate this change in a efficient way. We only added the change to the changelog. We removed that feature due to some conflicts with some very popular plugins which we couldn't fix without "hacking" those plugins, which we won't do. We have many support requests regarding that, so we decided to remove it for now. 

We are sorry to remove a feature that seems to be useful for you. We do have plans to restore it, you can follow the progress on the following issue: #29.

Im closing this issue, but feel free to contact us if you have any question.

**Comment by JulieBanu** [comment]
Hi @andergmartins,

Thank you for your feedback. 
If this feature was removed then it should be removed from the website:
https://publishpress.com/knowledge-base/assign-wordpress-posts-no-author/

Regards,
Iuliana Banu

**Comment by andergmartins** [comment]
Makes sense @JulieBanu thanks for spotting this. 
We are going to fix it.
