### ISSUE TITLE
Activating the plugin crashes the 'Edit Post' feature

### ISSUE THREAD

**Issue by qrjun** [publishpress/PublishPress-Authors#567]
![image](https://user-images.githubusercontent.com/68153790/152346172-050de1cd-6134-418f-abfc-9e8f0c83b98d.png)

When I disable the plugin, my gutenberg editor works just fine:

![image](https://user-images.githubusercontent.com/68153790/152346808-abc70bcb-1be0-4d18-a620-6aebcb8c7d0e.png)

**Comment by stevejburge** [comment]
Hi @qrjun 

Sorry, this is lacking key information for a Github issue.

Please reopen this ticket with detailed information so that someone else can re-create the problem. When you created a bug report, you should have seen this template:






If you have found a bug in the code of our plugins and want to report it, this is the best place! 

However, please note that this option is for genuine bugs that can be reproduced on other sites. This is not for support questions about your site. We will close questions if they are about issues with your site.

We have "PublishPress members" support available for commercial users and "Non-members" support for non-commercial users: https://publishpress.com/publishpress-support/

## Expected Behavior




## Current Behavior




## Possible Solution




## Steps to Reproduce (for bugs)



1.
2.
3.
4.

## Context




## Your Environment



* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:
