### ISSUE TITLE
Only allow one author mapped to each user

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#64]
I came across a site where one WordPress user was mapped to around a dozen different Author accounts.

We should add a setting "Only allow a WordPress user to be mapped to one Author".

If people really want to change that, they can uncheck the box.

**Comment by andergmartins** [comment]
@ojopaul I merged the PR that implemented the fix for this, but I just tested again and it only works when creating a new author. It is not validating if I edit an existent author.

## How to reproduce

* Create a guest author
* Edit the guest author profile
* Select a user that is already mapped to another author
* Save

It will save and allow two authors mapped to the same user.
