### ISSUE TITLE
Allow users to limit the length of a bio in a layout

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#754]
Can we allow users to restrict how a long the bio is in their layouts?

**Comment by ojopaul** [comment]
@stevejburge this has been implemented and it can be use in both twig layout template or php author object.

Here's a note for documentation.

We introduced a new method get_description() which can be use on any author object or layout as `$author->get_description()` or `author->get_description()` incase it's twig template.

It accepted two parameters with none required.
1. Limit: Integer to define description limits
2. End: This is default to `...` and it's the last characters appended at the end of description incase it's truncated due to limit.

Example usage with parameters:
1. `author->get_description(150)` will limit the description to first 150 characters and `...` will be appended at the end
2. `author->get_description(150, '')` will limit the description to first 150 characters without appending the default `...` at the end
3. `author->get_description(150, '...,')` will limit the description to first 150 characters and append specified ..., at the end if limit is exceeded
