### ISSUE TITLE
Can't use Search Box on default layouts

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#836]
Shortcodes like this don't currently show the search box:

[publishpress_authors_list layout="boxed" search_box="true"]

[publishpress_authors_list layout="inline" search_box="true"]

**Comment by ojopaul** [comment]
@stevejburge I just tested this and it's working.

Are you testing in pro? If so, kindly note the search and pagination were just updated for the layouts which shows the token is not present in previous layouts. So, if you want the updated layout, you can delete the previous version and use "Create default layouts" in settings to generate the layout with updated token.

Note, the reason i don't think of auto updating the layouts data is because some may have updated their layouts and doing so, their changes will be lost.

So, can you confirm if this is the issue?

**Comment by stevejburge** [comment]
Hi @ojopaul 

Yes, I'm testing in Authors Pro. Here's the shortcode. If I change it to authors_recent, the search shows:
<img width="527" alt="Screen Shot 2022-08-09 at 7 02 58 PM" src="https://user-images.githubusercontent.com/3868028/183776565-b630bc22-9845-4910-94c8-6a56e3a4aa9e.png">

Here's the output of the shortcode above:
<img width="706" alt="Screen Shot 2022-08-09 at 7 04 10 PM" src="https://user-images.githubusercontent.com/3868028/183776609-834991ed-e8c1-431d-9cba-30d6bea808f7.png">

**Comment by ojopaul** [comment]
@stevejburge Did you confirm the last condition and statement? That is, the layouts are newly updated ones and not old layout in settings > layouts?

**Comment by stevejburge** [comment]
I do see "Search" loading for Author Recent, but not for Boxed:
<img width="728" alt="Screen Shot 2022-08-09 at 7 10 46 PM" src="https://user-images.githubusercontent.com/3868028/183777266-932162fc-8d3e-4bd3-96ab-8b6d7d305dc9.png">


<img width="932" alt="Screen Shot 2022-08-09 at 7 11 22 PM" src="https://user-images.githubusercontent.com/3868028/183777297-9df55e47-abaf-4141-96d1-38d5ee50db65.png">

**Comment by ojopaul** [comment]
That's what i was trying to explain but I'll do so again.

Search and pagination were just updated for the layouts files which shows the token is not present in previous layouts. So, if you want the updated layout, you can delete the previous version for the layout in 'layouts' tab and use "Create default layouts" in settings > maintenance to generate the layout with updated token.

Wondering why we didn't update the layout for pro users automatically? 
The reason is because some sites may have customise their layouts and modify it and if we should auto update, their changes will be lost and that's why it needed to be done manually unless you want us to provide specific solution for it but auto update won't be ideal as that'll remove whatever changes they've made to the default layout

@stevejburge

**Comment by stevejburge** [comment]
That makes sense, thanks @ojopaul 

It also confirms that we need to change our current approach to layouts. I'll move this to the relevant milestone
