### ISSUE TITLE
Add settings to disable mapped user check when creating author

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#885]
I think we may need a setting to disable this block, please:

![erro-ae6ce461e7b6e2ba274812a097ab0e3c](https://user-images.githubusercontent.com/3868028/186720138-6a54333b-e964-4164-ac1d-c999ff4478f0.jpg)

It can cause problems with WPML users:

>  I have a website in 3 languages: Portuguese, English and French. When placing a user in English or Portuguese it triggers the following error message as shown in the attached image. This did not happen in previous versions. We need these users working normally in order to proceed. What can we do to fix this problem?

**Comment by ojopaul** [comment]
We've had discussions on https://github.com/publishpress/PublishPress-Authors/issues/73 and https://github.com/publishpress/PublishPress-Authors/issues/64 to not allow option to map more than one user but I'll add this settings since it conflict some plugins usage but that shows the site may run into some other issues mentioned that leads to restriction to one author per user due to the way authors works and this feature should only be used when necessary.

@stevejburge

**Comment by stevejburge** [comment]
Thanks @ojopaul 

Yes, this is part of what makes the multiple authors feature difficult. Adding a setting is the best idea here
